name: Build and Scan Image with Sysdig Secure Inline Scanner v1
on: 
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/hello-world

jobs:
  Build-Push-Scan:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata tag set
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} 
          tags: |
            type=raw,value={{branch}}
# type=semver,pattern={{ version }},priority=900
# type=semver,pattern={{major}}.{{minor}},priority=900
# type=ref,enable=${{ github.event_name == 'create' && startsWith(github.ref, 'refs/tags/v' ) }},event=tag,priority=100
            
          labels: |
            org.opencontainers.image.title=hello-world
            maintainer=michael.scholl@sysdig.com

      - name: Set up Docker Buildx
        if: ${{ !env.ACT }}
        uses: docker/setup-buildx-action@v2

      - name: Build hello-world image
        if: ${{ !env.ACT }}
        uses: docker/build-push-action@v3
        id: build
        with:
          push: false
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: push hello-world image
        run: |
          docker image ls

      - name: Scan image with Sysdig Scanner v2
        run: |
          export SECURE_API_TOKEN=${{ secrets.SECURE_API_TOKEN }}
          VERSION=$(curl -L -s https://download.sysdig.com/scanning/sysdig-cli-scanner/latest_version.txt)
          curl -LO "https://download.sysdig.com/scanning/bin/sysdig-cli-scanner/${VERSION}/linux/amd64/sysdig-cli-scanner"
          chmod +x ./sysdig-cli-scanner
          ./sysdig-cli-scanner --apiurl ${{ secrets.SYSDIG_SECURE_URL }} docker://${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:main

      - name: push hello-world image
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:main

      