name: Build and Scan Image with Sysdig Secure Inline Scanner v1
on: 
  push:
    tags:
      - 'v*'
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Build-Docker-Artifact:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Docker metadata tag set
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: hello-world
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{ version }}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,prefix={{ branch }}-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build hello-world image
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=docker, dest=${{ github.workspace }}/hello-world.tar

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: hello-world
          path: ${{ github.workspace }}/hello-world.tar
          retention-days: 5

  Run-Sysdig-Inline-Scanner-v1:
    runs-on: ubuntu-latest
    needs:
      - Build-Docker-Artifact
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with: 
          name: hello-world
          path: ${{ github.workspace }}

      - name: Add short_sha property with commit short sha
        id: sha
        run: echo "::set-output name=short_sha::$(echo ${{ github.sha }} | cut -c1-8)"

      - name: Scan image with Sysdig Scanner
        uses: sysdiglabs/scan-action@v3
        id: scan
        with:
          image-tag: hello-world:main-${{ steps.sha.outputs.short_sha }}
          sysdig-secure-url: ${{ secrets.SYSDIG_SECURE_URL }}
          sysdig-secure-token: ${{ secrets.SECURE_API_TOKEN }}
          input-type: docker-archive
          input-path: ${{ github.workspace }}/hello-world.tar
          ignore-failed-scan: true
          extra-parameters: -c 
          #--write-json ${{ github.workspace }}/hello-world-main-${{ steps.sha.outputs.short_sha }}.json

      - run: mv ${{ github.workspace }}/report.json ${{ github.workspace }}/hello-world-main-${{ steps.sha.outputs.short_sha }}.json

      #- run: docker run --env SYSDIG_ADDED_BY='cicd-inline-scan' -v /tmp:/tmp --rm quay.io/sysdig/secure-inline-scan:2 hello-world:main-${GITHUB_SHA::7} --sysdig-url https://us2.app.sysdig.com --sysdig-token $SECURE_API_TOKEN --storage-type docker-archive --storage-path /tmp/hello-world.tar --write-json /tmp/image-results.json -c --report-folder /tmp
      #  env:
      #    SECURE_API_TOKEN: ${{ secrets.SECURE_API_TOKEN }}
      #  continue-on-error: true
      - name: Upload image results JSON
        uses: actions/upload-artifact@v2
        with:
          name: image-scan-results-json
          path: ${{ github.workspace }}/hello-world-main-${{ steps.sha.outputs.short_sha }}.json


  Post-Sysdig-Inline-Scan-Results:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    needs: 
      - Run-Sysdig-Inline-Scanner-v1
    steps:

      - run: jq .issue ${{ github.event_path }}

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: image-scan-results-json
          path: ${{ github.workspace }}

      - name: Add short_sha property with commit short sha
        id: sha
        run: echo "::set-output name=short_sha::$(echo ${{ github.sha }} | cut -c1-8)"

      - run: jq .log ${{ github.workspace }}/hello-world-main-${{ steps.sha.outputs.short_sha }}.json
      - run: jq .status ${{ github.workspace }}/hello-world-main-${{ steps.sha.outputs.short_sha }}.json
        

#  Run-Sysdig-Inline-Scanner-v2:
#    runs-on: ubuntu-latest
#    steps:
#      - run: wget "https://download.sysdig.com/scanning/inlinescan/inlinescan_$(curl -L -s https://download.sysdig.com/scanning/inlinescan/latest_version.txt)_linux_amd64" -O ./sysdig-inline-scanner
#      - run: chmod +x ./sysdig-inline-scanner
#      - name: Build hello-world image
#        uses: docker/build-push-action@v2.7.0
#        with:
#          push: false
#          tags: ${{ secrets.IMAGE_REPOSITORY }}/hello-world:latest
#      - run: ./sysdig-inline-scanner --apiurl https://us2.app.sysdig.com ${{ secrets.IMAGE_REPOSITORY }}/hello-world:latest --full-vulns-table
#        env:
#          SECURE_API_TOKEN: ${{ secrets.SECURE_API_TOKEN }}
        
          

